name: .NET

#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name:  Intall/Update LivingDocs
      run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI    
      
    - name: Generate Living Docs  
      run: livingdoc test-assembly RestsharpZip/bin/Debug/netcoreapp3.1/RestsharpZip.dll -t RestsharpZip/bin/Debug/netcoreapp3.1/TestExecution.json      
      
    - name: Archive LivingDocs artefact
      uses: actions/upload-artifact@v2
      with:
        name: Living docs report
        path: /home/runner/work/ZipRestSharp/ZipRestSharp/LivingDoc.html
      
      # upload report as an artefact
    - name: Archive specflow report
      uses: actions/upload-artifact@v2
      with:
        name: specflow-execution-report
        path: /home/runner/work/ZipRestSharp/ZipRestSharp/RestsharpZip/TestResults/MyReportWithPieChart.html
