name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
      # upload report as an artefact
    - name: Archive execution report
      uses: actions/upload-artifact@v2
      with:
        name: specflow-execution-report
        path: /home/runner/work/SeleniumDotNetCore/SeleniumDotNetCore/WebApp/TestResults/MyReportWithPieChart.html
